### ISSUE TITLE
Adding geom_sf() on top of PlotSvalbard::basemap()?

### ISSUE THREAD

**Issue by MirzaCengic** [MikkoVihtakari/PlotSvalbard#1] opened 2019-02-19 13:25 UTC
Hi Mikko,

great package, thanks for the effort. I wanted to create some maps using the templates offered by plot svalbard, but I would like to add additional layers on top (few polygon layer, point layer, and a raster layer). Normally I would stack up everything with ggplot and geom_sf, but I cannot find a way where this approach works with `PlotSvalbard::basemap()`.
I get the error message posted below, even though the layer is projected to `map_projection("panarctic")`, and it seems that ggplot is looking for lat-long columns, although geom_sf uses the geometry column to plot the layer. Is this feature even possible? I was looking into `add_land()`, but I'm not sure how to use it. Alternatively, I was thinking just to use the ggplot code used by plotsvalbard (if I'm not mistaken, that's in map_cmd.R?). I can make a reprex if it's easier for you to see what I'm trying to do.

Cheers,
Mirza.

```
Coordinate system already present. Adding new coordinate system, which will replace the existing one.
Error in FUN(X[[i]], ...) : object 'long' not found
```

**Comment by MikkoVihtakari** [comment] 2019-02-19 13:40
I have not used `geom_sf` with the package. It is difficult to know where the problem is without a reproducible example. You can get the data used by all the layers by `basemap("panarctic", plot = FALSE)`. You can also just plot your points, polygons and rasters and then add `+ add_land()` at the end. Use `inherit.aes = FALSE` for polygons.

**Comment by MikkoVihtakari** [comment] 2019-02-25 06:44
@MirzaCengic, did you manage to solve the issue?

**Comment by MikkoVihtakari** [comment] 2019-03-01 09:39
Since there was no feedback, I will close this issue. Open a new issue with a reproducible example, if needed.

**Closed as completed by MikkoVihtakari** 2019-03-01 09:39 UTC

**Comment by MirzaCengic** [comment] 2019-03-01 11:16
Sorry for late reply Mikko, yes I managed to do what I needed in the end, but I didn't use PlotSvalbard. Thank you in any case.
